language: ruby
rvm:
 - 2.3.0
services:
  - postgresql
before_script:
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:schema:dump RAILS_ENV=test
  - bundle exec rake db:drop RAILS_ENV=test
  - bundle exec rake db:create RAILS_ENV=test
  - bundle exec rake db:migrate RAILS_ENV=test
  # - psql -c 'create database travis_ci_test;' -U postgres
